[package]
name = "firstrade-server-example"
version = "0.1.0"
edition = "2024"

[dependencies]
firstrade = { path = "../../../firstrade" }
anyhow = "1.0"
tokio = { version = "1.47", features = ["full"] }
axum = "0.8"
